- hosts: localhost
  gather_facts: false
  vars:
   host: "192.168.210.11"
   username: "admin"
   password: "fortinet"
   vdom: "root"
  tasks:
  - name: Configure HA.
    fortios_system_ha:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "False"
      system_ha:
        hbdev: '"port8" 80 "port9" 90'

  - name: Configure HA.
    fortios_system_ha:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "False"
      system_ha:
    check_mode: yes
    register: fortios_system_ha_result

  - debug:
      var: fortios_system_ha_result
