- hosts: localhost
  gather_facts: false
  vars:
   host: "192.168.210.11"
   username: "admin"
   password: "fortinet"
   vdom: "root"
  tasks:
  - name: Perform firmware upgrade with local firmware file.
    fortios_system_firmware_upgrade:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "True"
      system_firmware:
        filename: "/workspaces/ansible_generator/firmware/FGT_VM64_KVM-v6-build0163-FORTINET.out"
        source: "upload"
