- hosts: localhost
  gather_facts: false
  vars:
   host: "192.168.210.11"
   username: "admin"
   password: "fortinet"
   vdom: "root"
  tasks:
  - name: List of checksums for members of HA cluster.
    fortios_system_ha_checksums_select:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      system_ha_checksums:
    register: fortios_system_ha_checksums_select_return
  - debug:
      var: fortios_system_ha_checksums_select_return