- hosts: localhost
  vars:
   host: "192.168.210.11"
   username: "admin"
   password: "fortinet"
   vdom: "root"
  tasks:
  - name: Retrieve basic system status.
    fortios_system_status_select:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "True"
      system_status:
    register: fortios_system_status_select_result
  - debug:
      var: fortios_system_status_select_result
