- hosts: localhost
  vars:
   host: "192.168.122.40"
   username: "admin"
   password: ""
   vdom: "root"
  tasks:
  - name: Configure virtual IP for IPv4.
    fortios_firewall_vip:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "False"
      state: "present"
      firewall_vip:
        name: "1"
        type: static_nat
        dns_mapping_ttl: 0
        ldb_method: static
        extip: 1.1.1.1
        mappedip:
        - range: 10.10.10.10
        extintf: port1
        arp_reply: enable
        protocol: tcp
        extport: 0-65535
        mappedport: 0-65535
  - name: Configure IPv4 virtual IP groups.
    fortios_firewall_vipgrp:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "False"
      state: "present"
      firewall_vipgrp:
        name: My Vip Group
        interface: port1
        color: 0
        comments: simple group
        member:
        - name: '1'

