- hosts: localhost
  vars:
   host: "192.168.122.40"
   username: "admin"
   password: ""
   vdom: "root"
  tasks:
  - name: Configure IPv4 addresses.
    fortios_firewall_address:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "False"
      firewall_address:
        state: "present"
        name: ip_test_example
        subnet: 10.210.4.0/24
        type: iprange
        start_ip: 10.210.4.208
        end_ip: 10.210.4.220
        fqdn: ''
        country: ''
        wildcard_fqdn: ''
        cache_ttl: 0
        wildcard: 10.210.4.208 10.210.4.220
        tenant: ''
        organization: ''
        epg_name: ''
        subnet_name: ''
        sdn_tag: ''
        policy_group: ''
        comment: ''
        visibility: enable
        associated_interface: ssl.root
        color: 0
        filter: ''
        obj_id: ''
        list: []
        tagging: []
        allow_routing: disable