- hosts: localhost
  vars:
   host: "192.168.122.40"
   username: "admin"
   password: ""
   vdom: "root"
  tasks:
  - name: Configure virtual IP for IPv6.
    fortios_firewall_vip6:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "False"
      firewall_vip6:
        state: "present"
        name: vipIPv6
        comment: new vip
        type: static_nat
        src_filter: []
        extip: "::1823:4324:436a-::1823:4324:4400"
        mappedip: "::1032:2000:2134:2-::1032:2000:2134:98"
        arp_reply: enable
        portforward: enable
        protocol: tcp
        extport: 250-260
        mappedport: 8250-8260
        color: 0
        ldb_method: static
        persistence: none
        realservers: []
        http_cookie_domain_from_host: disable
        http_cookie_domain: ''
        http_cookie_path: ''
        http_cookie_generation: 0
        http_cookie_age: 60
        http_cookie_share: same_ip
        https_cookie_secure: disable
        http_multiplex: disable
        http_ip_header: disable
        http_ip_header_name: ''
        outlook_web_access: disable
        weblogic_server: disable
        websphere_server: disable
        ssl_mode: half
        ssl_certificate: ''
        ssl_dh_bits: '2048'
        ssl_algorithm: high
        ssl_cipher_suites: []
        ssl_server_algorithm: client
        ssl_server_cipher_suites: []
        ssl_pfs: require
        ssl_min_version: tls_1.1
        ssl_max_version: tls_1.2
        ssl_server_min_version: client
        ssl_server_max_version: client
        ssl_send_empty_frags: enable
        ssl_client_fallback: enable
        ssl_client_renegotiation: secure
        ssl_client_session_state_type: both
        ssl_client_session_state_timeout: 30
        ssl_client_session_state_max: 1000
        ssl_server_session_state_type: both
        ssl_server_session_state_timeout: 60
        ssl_server_session_state_max: 100
        ssl_http_location_conversion: disable
        ssl_http_match_host: enable
        ssl_hpkp: disable
        ssl_hpkp_primary: ''
        ssl_hpkp_backup: ''
        ssl_hpkp_age: 5184000
        ssl_hpkp_report_uri: ''
        ssl_hpkp_include_subdomains: disable
        ssl_hsts: disable
        ssl_hsts_age: 5184000
        ssl_hsts_include_subdomains: disable
        monitor: []
        max_embryonic_connections: 1000
