- hosts: localhost
  vars:
   host: "192.168.122.40"
   username: "admin"
   password: ""
   vdom: "root"
  tasks:
  - name: Configure DHCP servers.
    fortios_system_dhcp_server:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "False"
      state: "present"
      system_dhcp_server:
        auto_configuration: "disable"
        default_gateway: "10.20.1.1"
        dns_server1: "8.8.8.8"
        dns_server2: "8.8.4.4"
        dns_service: "local"
        domain: "mydomain.com"
        forticlient_on_net_status: "disable"
        id:  "1"
        interface: "port2"
        lease_time: "300"
        netmask: "255.255.255.0"
        ntp_server1: "10.10.1.1"
        ntp_service: "local"
        options:
         -  code: "42"
            id:  "1"
            type: "hex"
            value: "92"
        server_type: "regular"
        status: "disable"
        tftp_server:
         - tftp_server: "10.1.1.1"
        timezone_option: "disable"
        vci_match: "disable"
